import json
import time
import random
from confluent_kafka import Producer

COMMENTS = [
    "I love this!",
    "This is terrible.",
    "What a great day!",
    "I hate this!",
    "Amazing work!",
    "This makes no sense.",
    "I’m so happy right now.",
    "Worst experience ever.",
    "Feeling grateful today.",
    "This ruined my whole mood.",
    "Can’t believe how awesome this is!",
    "I’m extremely disappointed.",
    "Such a beautiful moment.",
    "Why is everything so complicated?",
    "Absolutely thrilled!",
    "This is the worst idea possible.",
    "I’m proud of myself today.",
    "Nothing is going right.",
    "Best news ever!",
    "I wish I had never seen this.",
    "I feel inspired!",
    "Not impressed at all.",
    "This made my day.",
    "This is unacceptable.",
    "I’m full of hope again.",
    "This frustrates me so much.",
    "Just wonderful.",
    "What a disaster.",
    "So excited about this!",
    "I regret doing this.",
    "This is perfect!",
    "I can't stand this.",
    "Very impressive work.",
    "I’m tired of this nonsense.",
    "So peaceful and calming.",
    "I feel completely lost.",
    "This is incredible!",
    "How disappointing.",
    "Couldn't be happier!",
    "What a waste of time.",
    "This is pure joy.",
    "This is making me angry.",
    "Absolutely loved it!",
    "I wish this never happened.",
    "I’m feeling optimistic.",
    "This is such a mess.",
    "Best thing I’ve seen all week!",
    "This is ruining everything.",
    "Honestly, amazing.",
    "I can't believe how bad this is.",
    "Feeling super good today.",
    "Terrible execution.",
    "This is lovely!",
    "I’m annoyed beyond words.",
    "What a pleasant surprise!",
    "This is just awful.",
    "I’m motivated again.",
    "Worst decision ever.",
    "This makes me so happy.",
    "I don’t like this at all.",
    "Such positive vibes!",
    "This is totally unacceptable.",
    "So heartwarming.",
    "I can't take this anymore.",
    "This exceeded my expectations!",
    "Everything about this is wrong.",
    "I’m truly impressed.",
    "This is depressing.",
    "This brings me joy.",
    "I seriously hate this.",
    "Such a great feeling!",
    "This is so disappointing.",
    "Absolutely fantastic!",
    "Completely useless.",
    "Feeling blessed today.",
    "This is such a letdown.",
    "Pure happiness.",
    "I've had enough of this.",
    "This just made my whole week!",
    "Terrible, just terrible.",
    "This is the best!",
    "I’m so embarrassed for them.",
    "This is phenomenal!",
    "I can’t handle this negativity.",
    "Feeling on top of the world!",
    "This is painfully bad.",
    "Such an amazing experience!",
    "Why would anyone do this?",
    "I feel great!",
    "I’m really upset about this.",
    "This is next-level awesome.",
    "Worst thing I’ve seen today.",
    "Feeling refreshed!",
    "This ruined my day.",
    "This is so exciting!",
    "I absolutely despise this.",
    "What an incredible moment!",
    "This is ridiculous.",
    "Today was amazing!",
    "I’m so done with this.",
    "This is wonderful news.",
    "This feels terrible.",
    "Such joy!",
    "This makes me furious.",
    "Absolutely beautiful!",
    "This is the definition of bad.",
    "I’m extremely happy today.",
    "I can't stop thinking about how awful this is.",
    "This is so wholesome.",
    "Everything about this sucks.",
    "Feeling super inspired!",
    "This is unbelievably bad.",
    "Best vibes only!",
    "I hate everything about this.",
    "This made me smile.",
    "What a terrible mistake.",
    "I’m loving the energy!",
    "This is so frustrating.",
    "Such a nice gesture.",
    "This is absolutely horrible.",
    "Feeling calm and happy.",
    "I’m ridiculously annoyed.",
    "This is epic!",
    "This couldn't be worse.",
    "So proud of this!",
    "This is trash.",
    "I’m delighted!",
    "I'm losing my patience.",
    "This made my morning.",
    "I regret clicking this.",
    "This is incredible news!",
    "Everything here is awful.",
    "Feeling super grateful.",
    "This needs to stop.",
    "Such brilliance!",
    "I’m very disappointed.",
    "This is pure happiness.",
    "This is such a fail.",
    "Feeling uplifted!",
    "This was a huge mistake.",
    "Absolutely stunning.",
    "I’m so frustrated.",
    "This is top tier!",
    "This is really bad.",
    "I love the positivity!",
    "I can’t stand this anymore.",
    "This looks great!",
    "This is completely unacceptable.",
    "I feel amazing!",
    "This is a nightmare.",
    "Wow, this is incredible!",
    "I’m so over this.",
    "This is unbelievably great!",
    "This makes me uncomfortable.",
    "Amazing news!",
    "I wish I didn’t see this.",
    "Feeling wonderful today!",
    "This is the worst thing ever.",
    "This is so fun!",
    "I hate how this turned out.",
    "Such an exciting update!",
    "This is a total disaster.",
    "I’m thrilled!",
    "This is completely pointless.",
    "Such a refreshing idea.",
    "I deeply dislike this.",
    "Pure excitement!",
    "This is absurd.",
    "Feeling so positive!",
    "This is a huge disappointment.",
    "Love the energy here!",
    "I can’t believe how awful this is.",
    "This is pure gold!",
    "This is too much negativity.",
    "Feeling fantastic!",
    "What a terrible outcome.",
    "This is brilliant!",
    "This is not good at all.",
    "So much joy in one post.",
    "This ruined everything.",
    "I absolutely adore this!",
    "This is such a mess.",
    "Feeling motivated today!",
    "Everything about this is awful.",
    "This is insanely good!",
    "This bothers me so much.",
    "Such an impressive job!",
    "I dislike this strongly.",
    "Feeling hopeful again!",
    "This is a complete failure.",
    "This is unbelievably awesome!",
    "Nothing here makes sense.",
    "Feeling energized!",
    "This is embarrassing.",
    "This is incredibly heartwarming!",
    "I’m irritated.",
    "This is pure magic.",
    "Worst idea ever.",
    "I’m so glad this happened.",
    "This is extremely disappointing.",
    "Such a beautiful update!",
    "This is really annoying.",
    "I’m feeling joyful.",
    "I absolutely hate this.",
    "This feels amazing!",
    "This feels wrong.",
    "In love with this moment!",
    "I can't stop cringing.",
    "This is so lovely!",
    "This is a complete mess.",
    "I'm genuinely happy.",
    "This made everything worse.",
    "Totally uplifting!",
    "This is pathetic.",
    "I’m so excited!",
    "This is giving me a headache.",
    "This is too cute!",
    "I’m extremely bothered.",
    "This just brightened my day!",
    "I regret everything.",
    "This is amazing!!",
    "Nothing good about this.",
    "So wholesome!",
    "This is an absolute failure.",
    "I’m loving this vibe.",
    "This is terrible news.",
    "Such a cool idea!",
    "I can't tolerate this.",
    "I'm smiling so much!",
    "This is a huge mistake.",
    "This fills me with joy.",
    "This is worse than I expected."
]


USERS = [f"user_{i}" for i in range(1, 101)]

producer = Producer({"bootstrap.servers": "localhost:9092"})

def send_message():
    msg = {
        "user_id": random.choice(USERS),
        "comment": random.choice(COMMENTS)
    }
    producer.produce("twitter-comments", json.dumps(msg).encode("utf-8"))
    producer.flush()
    print("Sent:", msg)

def main():
    print("Client started.")
    for _ in range(random.randint(5, 200)):  # Aleatory number of messages to send
        send_message()
        time.sleep(random.uniform(0.5, 3))  # Aleatory delay between messages
    print("Client finished.")

if __name__ == "__main__":
    main()
